/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;

public class GetIpDataRequestBuilder {

    private JsonNullable<String> ipAddress = JsonNullable.undefined();
    private final SDKMethodInterfaces.MethodCallGetIpData sdk;

    public GetIpDataRequestBuilder(SDKMethodInterfaces.MethodCallGetIpData sdk) {
        this.sdk = sdk;
    }

    public GetIpDataRequestBuilder ipAddress(String ipAddress) {
        Utils.checkNotNull(ipAddress, "ipAddress");
        this.ipAddress = JsonNullable.of(ipAddress);
        return this;
    }

    public GetIpDataRequestBuilder ipAddress(JsonNullable<String> ipAddress) {
        Utils.checkNotNull(ipAddress, "ipAddress");
        this.ipAddress = ipAddress;
        return this;
    }

    public GetIpDataResponse call() throws Exception {

        return sdk.getIpData(
            ipAddress);
    }
}
