/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;

public class GetIpRequestBuilder {

    private final SDKMethodInterfaces.MethodCallGetIp sdk;

    public GetIpRequestBuilder(SDKMethodInterfaces.MethodCallGetIp sdk) {
        this.sdk = sdk;
    }

    public GetIpResponse call() throws Exception {

        return sdk.getIpDirect();
    }
}
