/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.Response;
import org.openapis.openapi.utils.Utils;

public class GetIpDataResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Successful Response
     */
    private Optional<? extends ResponseGetJsonDataJsonGet> responseGetJsonDataJsonGet;

    @JsonCreator
    public GetIpDataResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends ResponseGetJsonDataJsonGet> responseGetJsonDataJsonGet) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(responseGetJsonDataJsonGet, "responseGetJsonDataJsonGet");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.responseGetJsonDataJsonGet = responseGetJsonDataJsonGet;
    }
    
    public GetIpDataResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Successful Response
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ResponseGetJsonDataJsonGet> responseGetJsonDataJsonGet() {
        return (Optional<ResponseGetJsonDataJsonGet>) responseGetJsonDataJsonGet;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public GetIpDataResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetIpDataResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetIpDataResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Successful Response
     */
    public GetIpDataResponse withResponseGetJsonDataJsonGet(ResponseGetJsonDataJsonGet responseGetJsonDataJsonGet) {
        Utils.checkNotNull(responseGetJsonDataJsonGet, "responseGetJsonDataJsonGet");
        this.responseGetJsonDataJsonGet = Optional.ofNullable(responseGetJsonDataJsonGet);
        return this;
    }

    /**
     * Successful Response
     */
    public GetIpDataResponse withResponseGetJsonDataJsonGet(Optional<? extends ResponseGetJsonDataJsonGet> responseGetJsonDataJsonGet) {
        Utils.checkNotNull(responseGetJsonDataJsonGet, "responseGetJsonDataJsonGet");
        this.responseGetJsonDataJsonGet = responseGetJsonDataJsonGet;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetIpDataResponse other = (GetIpDataResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.responseGetJsonDataJsonGet, other.responseGetJsonDataJsonGet);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            responseGetJsonDataJsonGet);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetIpDataResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "responseGetJsonDataJsonGet", responseGetJsonDataJsonGet);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends ResponseGetJsonDataJsonGet> responseGetJsonDataJsonGet = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Successful Response
         */
        public Builder responseGetJsonDataJsonGet(ResponseGetJsonDataJsonGet responseGetJsonDataJsonGet) {
            Utils.checkNotNull(responseGetJsonDataJsonGet, "responseGetJsonDataJsonGet");
            this.responseGetJsonDataJsonGet = Optional.ofNullable(responseGetJsonDataJsonGet);
            return this;
        }

        /**
         * Successful Response
         */
        public Builder responseGetJsonDataJsonGet(Optional<? extends ResponseGetJsonDataJsonGet> responseGetJsonDataJsonGet) {
            Utils.checkNotNull(responseGetJsonDataJsonGet, "responseGetJsonDataJsonGet");
            this.responseGetJsonDataJsonGet = responseGetJsonDataJsonGet;
            return this;
        }
        
        public GetIpDataResponse build() {
            return new GetIpDataResponse(
                contentType,
                statusCode,
                rawResponse,
                responseGetJsonDataJsonGet);
        }
    }
}
