/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import org.openapis.openapi.models.components.ErrorResponse;
import org.openapis.openapi.models.components.GeoIPResponse;
import org.openapis.openapi.utils.OneOfDeserializer;
import org.openapis.openapi.utils.TypedObject;
import org.openapis.openapi.utils.Utils.JsonShape;
import org.openapis.openapi.utils.Utils.TypeReferenceWithShape;
import org.openapis.openapi.utils.Utils;

/**
 * ResponseGetJsonDataJsonGet
 * 
 * <p>Successful Response
 */
@JsonDeserialize(using = ResponseGetJsonDataJsonGet._Deserializer.class)
public class ResponseGetJsonDataJsonGet {

    @JsonValue
    private TypedObject value;
    
    private ResponseGetJsonDataJsonGet(TypedObject value) {
        this.value = value;
    }

    public static ResponseGetJsonDataJsonGet of(GeoIPResponse value) {
        Utils.checkNotNull(value, "value");
        return new ResponseGetJsonDataJsonGet(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<GeoIPResponse>(){}));
    }

    public static ResponseGetJsonDataJsonGet of(ErrorResponse value) {
        Utils.checkNotNull(value, "value");
        return new ResponseGetJsonDataJsonGet(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<ErrorResponse>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code org.openapis.openapi.models.components.GeoIPResponse}</li>
     * <li>{@code org.openapis.openapi.models.components.ErrorResponse}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseGetJsonDataJsonGet other = (ResponseGetJsonDataJsonGet) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<ResponseGetJsonDataJsonGet> {

        public _Deserializer() {
            super(ResponseGetJsonDataJsonGet.class, false,
                  TypeReferenceWithShape.of(new TypeReference<GeoIPResponse>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<ErrorResponse>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(ResponseGetJsonDataJsonGet.class,
                "value", value);
    }
 
}

