/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.openapitools.jackson.nullable.JsonNullable;

public class SDKMethodInterfaces {

    public interface MethodCallGetIp {
        GetIpResponse getIpDirect() throws Exception;
    }

    public interface MethodCallGetIpData {
        GetIpDataResponse getIpData(
            JsonNullable<String> ipAddress) throws Exception;
    }
}
